// 225 standard cards
export const standardCards: string[] = [
  // === POLITICI ITALIANI E INTERNAZIONALI (30) ===
  "Silvio Berlusconi",
  "Donald Trump",
  "Vladimir Putin",
  "Giorgia Meloni",
  "Matteo Salvini",
  "Papa Francesco",
  "Kim Jong-un",
  "Joe Biden",
  "Boris Johnson",
  "Emmanuel Macron",
  "Mario Draghi",
  "Giuseppe Conte",
  "Matteo Renzi",
  "Beppe Grillo",
  "Giulio Andreotti",
  "Bettino Craxi",
  "Barack Obama",
  "Angela Merkel",
  "Volodymyr Zelensky",
  "Jair Bolsonaro",
  "Luigi Di Maio",
  "Sergio Mattarella",
  "Romano Prodi",
  "Recep Erdogan",
  "Xi Jinping",
  "Narendra Modi",
  "Mario Monti",
  "Tony Blair",
  "Hugo Chavez",
  "Fidel Castro",

  // === MILIARDARI E TECH (20) ===
  "Elon Musk",
  "Jeff Bezos",
  "Mark Zuckerberg",
  "Bill Gates",
  "ChatGPT",
  "una Roomba impazzita",
  "il wifi del vicino",
  "un algoritmo di TikTok",
  "Alexa di Amazon",
  "Siri ubriaca",
  "un bitcoin in caduta libera",
  "un NFT inutile",
  "un hacker russo in mutande",
  "Google Maps in errore",
  "un aggiornamento di Windows",
  "un satellite di Starlink",
  "un robot di Boston Dynamics",
  "la batteria del telefono all'1%",
  "Steve Jobs fantasma",
  "un influencer da 12 follower",

  // === SPORT (25) ===
  "Cristiano Ronaldo",
  "Lionel Messi",
  "Diego Maradona",
  "Francesco Totti",
  "un arbitro di Serie B",
  "un ultras sfegatato",
  "Zlatan Ibrahimovic",
  "Valentino Rossi",
  "Usain Bolt",
  "Michael Jordan",
  "Roger Federer",
  "Rafael Nadal",
  "Mike Tyson",
  "Alberto Tomba",
  "Marco Pantani",
  "Gianluigi Buffon",
  "Roberto Baggio",
  "Paolo Maldini",
  "un calciatore di Serie D",
  "un tifoso del Napoli",
  "un tifoso della Juventus",
  "Lance Armstrong senza doping",
  "Michael Phelps",
  "Simone Biles",
  "un arbitro che fischia contro di te",

  // === POP CULTURE E FINZIONE (30) ===
  "Batman",
  "Superman",
  "SpongeBob",
  "Shrek",
  "Babbo Natale",
  "Harry Potter",
  "Darth Vader",
  "Iron Man",
  "Homer Simpson",
  "Bart Simpson",
  "il Joker",
  "Elsa di Frozen",
  "Indiana Jones",
  "James Bond",
  "Sherlock Holmes",
  "Pinocchio",
  "Gandalf",
  "Yoda",
  "il Grinch",
  "Dracula",
  "Frankenstein",
  "Hermione Granger",
  "Captain Jack Sparrow",
  "Walter White di Breaking Bad",
  "Tyrion Lannister",
  "Thanos",
  "un tiktoker da camera da letto",
  "un influencer del benessere",
  "Madonna",
  "Lady Gaga",

  // === PROFESSIONI E TIPI SOCIALI (35) ===
  "un prete di periferia",
  "un notaio addormentato",
  "un camorrista in vacanza",
  "un commercialista furbo",
  "un vegano militante",
  "un no-vax convinto",
  "un hipster di Pigneto",
  "un avvocato penalista",
  "un medico del pronto soccorso",
  "un farmacista che consiglia tutto",
  "un insegnante di sostegno",
  "un vigile urbano romano",
  "un carabiniere del nord",
  "un pompiere coraggioso",
  "un tassista romano polemico",
  "un barista napoletano",
  "un netturbino filosofo",
  "un portinaio ficcanaso",
  "un pizzaiolo verace",
  "un gelataio siciliano",
  "un sindacalista incazzato",
  "un burocrate italiano",
  "un cassiere delle poste",
  "un tirocinante non pagato",
  "un consulente di McKinsey",
  "un frate francescano",
  "un professore universitario fuori sede",
  "un personal trainer ossessivo",
  "un life coach su Instagram",
  "un sommelier snob",
  "un astrologo di Mediaset",
  "un politico in campagna elettorale",
  "un notaio che firma cose a caso",
  "un turista con la selfie stick",
  "un giornalista di tabloid",

  // === ANIMALI E OGGETTI ASSURDI (40) ===
  "un delfino intelligente",
  "un piccione di Roma",
  "un kebab alle 3 di notte",
  "un termosifone rotto",
  "un gatto su internet",
  "un cane randagio di quartiere",
  "un bradipo in vacanza",
  "un panda annoiato",
  "un polpo geniale",
  "una lumaca ottimista",
  "un procione del Bronx",
  "la Torre di Pisa",
  "un motorino scassato",
  "un treno di Trenitalia in ritardo",
  "un aperitivo milanese",
  "un cornetto al bar la mattina",
  "uno spritz a Venezia",
  "una pizza margherita doc",
  "un parmigiano reggiano DOP",
  "un caffè corretto alle 4 del pomeriggio",
  "un ombrello rotto nel vento",
  "una sedia di IKEA non montata",
  "un caricabatterie di Apple rotto",
  "un monolocale a Milano a 1500 euro",
  "un SUV nel centro storico",
  "un gratta e vinci vincente",
  "una multa del comune",
  "un meme del 2009 rispolverato",
  "un frigo vuoto il 27 del mese",
  "un coccodrillo in metropolitana",
  "una balena spiaggiata",
  "un tucano tropicale",
  "un cinghiale romano",
  "un camaleonte opportunista",
  "un granchio arrabbiato",
  "un pacco di pasta scaduta",
  "uno scooter parcheggiato sul marciapiede",
  "un coupon scaduto ieri",
  "una fotocamera usa e getta del 2003",
  "un termometro in estate a Palermo",

  // === CULTURA ITALIANA E STORIA (25) ===
  "Don Vito Corleone",
  "Totò",
  "Alberto Sordi",
  "Sophia Loren",
  "Federico Fellini",
  "un mafioso siciliano in crociera",
  "Pulcinella",
  "un gondoliere veneziano senza turisti",
  "un turista americano a Roma",
  "un milanese snob in vacanza",
  "un napoletano doc",
  "Dante Alighieri al bar",
  "Leonardo da Vinci al computer",
  "Michelangelo di fronte a IKEA",
  "Casanova su Tinder",
  "un nonno italiano al telefono",
  "una nonna italiana che cucina",
  "la mamma italiana al supermercato",
  "un pensionato al bar",
  "un turista giapponese al Vaticano",
  "uno studente fuorisede a Milano",
  "Marco Polo con Google Maps",
  "Garibaldi in metropolitana",
  "Giordano Bruno con Wikipedia",
  "un bambino di prima elementare",

  // === ASSURDO E ALTRO (20) ===
  "un astronauta sulla luna",
  "un fantasma del castello",
  "uno zombie che fa la spesa",
  "un alieno in visita sulla Terra",
  "un robot sentimentale",
  "l'ultimo biscotto del pacchetto",
  "una canzone che non riesci a toglierti dalla testa",
  "un'email di spam convincente",
  "una fila alle poste il lunedì mattina",
  "un Google Translate impazzito",
  "un'autocorrect traditrice",
  "il cugino di tuo cugino che sa tutto",
  "un party di compleanno a sorpresa mal riuscito",
  "il traffico di Roma alle 8 di mattina",
  "un momento imbarazzante al ristorante",
  "una riunione di condominio",
  "un documento scaduto in aeroporto",
  "un allarme antincendio falso alle 3 di notte",
  "un negozio che chiude per ferie ad agosto",
  "una previsione del meteo sbagliata",
];

// 75 explicit/NSFW cards — solo in modalità esplicita
export const explicitCards: string[] = [
  "una prostituta di lusso",
  "un pornoattore in crisi di identità",
  "una pornoattrice famosa",
  "un gigolò di mezza età",
  "un nudista convinto",
  "uno spogliarellista improvvisato",
  "una spogliarellista professionista",
  "Rocco Siffredi",
  "un vibratore dimenticato in valigia",
  "un preservativo bucato",
  "un film porno degli anni '90",
  "una rivista di Playboy del 1985",
  "un sito porno con troppi pop-up",
  "una chat erotica su WhatsApp",
  "un motel a ore senza troppe domande",
  "un'amante segreto",
  "un tradimento scoperto",
  "un profilo su OnlyFans",
  "un creatore di contenuti per adulti",
  "una MILF di quartiere",
  "un tipo che manda foto non richieste",
  "una relazione aperta mal gestita",
  "un voyeur di condominio",
  "un feticista delle scarpe",
  "una dominatrix professionale",
  "un orgasmo finto convincente",
  "una scena di sesso imbarazzante al cinema",
  "un'app di dating per persone sposate",
  "uno strip club di provincia",
  "un bacio passionale in ascensore",
  "un professore universitario troppo attraente",
  "un collega di lavoro con secondi fini",
  "un personal trainer con benefici",
  "uno scambio di coppia alle Maldive",
  "una fantasia erotica condivisa",
  "un sexting andato storto",
  "un video intimo trapelato",
  "una cronologia del browser imbarazzante",
  "un podcast sull'educazione sessuale",
  "un corso di tantra",
  "un giocattolo sessuale trovato in valigia dalla mamma",
  "una bondage session per principianti",
  "un lap dance improvvisato",
  "un flirt al convegno aziendale",
  "una scappatella in trasferta di lavoro",
  "una storia d'amore proibita",
  "un party a tema fetish",
  "uno streaker allo stadio",
  "una moglie troppo curiosa",
  "un marito ingenuo",
  "un amante geloso",
  "una posizione del kamasutra impossibile",
  "un massaggio erotico mal riuscito",
  "un gioco di ruolo erotico",
  "una fantasia proibita",
  "una notte brava a Milano",
  "un segreto di camera da letto",
  "un orgasmo multiplo non programmato",
  "una serata LGBT+ molto vivace",
  "un appuntamento su Grindr",
  "una serata in discoteca senza fini",
  "una sessione di yoga molto hot",
  "un medico con mani troppo esplorative",
  "un confessionale molto piccante",
  "una badante con troppe mansioni",
  "un idraulico chiamato per emergenze notturne",
  "un postino con consegne speciali",
  "una baby-sitter con sorprese",
  "un professore di educazione fisica troppo zelante",
  "una segretaria disinibita",
  "un appuntamento al buio finito bene",
  "una notte di passione tra colleghi",
  "un flirt sul treno delle 23",
  "una chat di WhatsApp di gruppo sbagliata",
  "un appuntamento segreto che diventa virale",
];

// Verify counts at runtime (dev sanity check)
if (process.env.NODE_ENV !== 'production') {
  if (standardCards.length !== 225) {
    console.warn(`⚠️  standardCards count: ${standardCards.length} (expected 225)`);
  }
  if (explicitCards.length !== 75) {
    console.warn(`⚠️  explicitCards count: ${explicitCards.length} (expected 75)`);
  }
}
